export { default as Authorization } from '../pages/Authorization/Authorization'
export { default as Project } from '../pages/Project/Project'
export { default as Employee } from '../pages/Employee/Employee'
export { default as Shaping } from '../pages/Shaping/Shaping'
export { default as Analitic } from '../pages/Analitic/Analitic'
export { default as Workspace } from '../pages/Workspace/Workspace'
export { default as Logout} from '../components/Logout/Logout'

export { default as Loading} from '../components/Loading/Loading'
export { default as AppRouter} from '../components/AppRouter/AppRouter'
export { default as Header} from '../components/Header/Header'
export { default as Footer} from '../components/Footer/Footer'
export { default as Main} from '../components/Main/Main'
export { default as Aside} from '../components/Aside/Aside'

export { default as ProjectCard} from '../components/ProjectCard/ProjectCard'
export { default as HeaderProject} from '../components/HeaderProject/HeaderProject'
export { default as ButtonSectionCard} from '../components/ButtonSectionCard/ButtonSectionCard'
export { default as Search} from '../components/Search/Search'
export { default as ButtonSetting} from '../components/ButtonSetting/ButtonSetting'
export { default as ButtonSort} from '../components/ButtonSort/ButtonSort'
export { default as EmployeeCard} from '../components/EmployeeCard/EmployeeCard'
export { default as CreateCard} from '../components/CreateCard/CreateCard'
export { default as PagginationCard} from '../components/PagginationCard/PagginationCard'
export { default as HeaderPageLine} from '../components/HeaderPageLine/HeaderPageLine'
export { default as EmptyCard} from '../components/EmptyCard/EmptyCard'
export { default as ChartLoading} from '../components/ChartLoading/ChartLoading'
export { default as PersonalInfo} from '../components/PersonalInfo/PersonalInfo'
export { default as PersonalLink} from '../components/PersonalLink/PersonalLink'
export { default as PagginationTechnology} from '../components/PagginationTechnology/PagginationTechnology'
export { default as ItemTechnology} from '../components/ItemTechnology/ItemTechnology'
export { default as ItemGrade} from '../components/ItemGrade/ItemGrade'
export { default as PagginationGrade} from '../components/PagginationGrade/PagginationGrade'
export { default as PagginationKnow} from '../components/PagginationKnow/PagginationKnow'
export { default as ItemLearn} from '../components/ItemLearn/ItemLearn'
export { default as CreateCardMini} from '../components/CreateCardMini/CreateCardMini'
export { default as SectionShaping} from '../components/SectionShaping/SectionShaping'
export { default as SelectProject} from '../components/SelectProject/SelectProject'
export { default as TableShaping} from '../components/TableS/TableShaping/TableShaping'
export { default as BlockStack} from '../components/TableS/BlockStack/BlockStack'
export { default as Person} from '../components/TableS/Person/Person'


export { default as Modal} from '../components/Modal/Modal/Modal'
export { default as NoneLine} from '../components/Modal/NoneLine/NoneLine'
export { default as Line} from '../components/Modal/Line/Line'
export { default as BlockText} from '../components/Modal/BlockText/BlockText'
export { default as Paggination} from '../components/Modal/Paggination/Paggination'
export { default as BlockEmployee} from '../components/Modal/BlockEmployee/BlockEmployee'
export { default as Nobody} from '../components/Modal/Nobody/Nobody'
export { default as Input} from '../components/Modal/Input/Input'
export { default as Select } from '../components/Modal/Select/Select'
export { default as SelectDS } from '../components/Modal/SelectDS/SelectDS'
export { default as BlockStackInput } from '../components/Modal/BlockStackInput/BlockStackInput'
export { default as ButtonCreate } from '../components/Modal/ButtonCreate/ButtonCreate'
